# Generated by Django 4.1.4 on 2023-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
