# Generated by Django 4.1.4 on 2023-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image", name="img_location", field=models.TextField(null=True),
        ),
    ]
