# Generated by Django 4.1.4 on 2023-02-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0002_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="stylebase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("styleID", models.CharField(max_length=20)),
                ("stylePrompt", models.CharField(max_length=255)),
                ("scale", models.IntegerField()),
                ("steps", models.IntegerField()),
            ],
        ),
    ]
