# Generated by Django 4.1.4 on 2023-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0002_alter_book_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
