# Generated by Django 4.1.4 on 2023-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0003_stylebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
