# Generated by Django 4.1.4 on 2023-02-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0004_alter_book_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="bookID",),
    ]
